// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsHWEKq2WTiIDzQ0t-K6l6Lhvvp1kQF_k',
    appId: '1:846220520693:web:0f9e55523959556172a9bc',
    messagingSenderId: '846220520693',
    projectId: 'smart-energy-meter-7b5a0',
    authDomain: 'smart-energy-meter-7b5a0.firebaseapp.com',
    databaseURL: 'https://smart-energy-meter-7b5a0-default-rtdb.firebaseio.com',
    storageBucket: 'smart-energy-meter-7b5a0.firebasestorage.app',
    measurementId: 'G-0S0YF6L472',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDva6KR1yG61svvmVDgI-DRqu84jevKjrg',
    appId: '1:846220520693:android:7e3aaee37a32ee5672a9bc',
    messagingSenderId: '846220520693',
    projectId: 'smart-energy-meter-7b5a0',
    databaseURL: 'https://smart-energy-meter-7b5a0-default-rtdb.firebaseio.com',
    storageBucket: 'smart-energy-meter-7b5a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx6aZ8WyrJmPuXishthAiTpxK-awVEn9A',
    appId: '1:846220520693:ios:293ec9815ab46b9572a9bc',
    messagingSenderId: '846220520693',
    projectId: 'smart-energy-meter-7b5a0',
    databaseURL: 'https://smart-energy-meter-7b5a0-default-rtdb.firebaseio.com',
    storageBucket: 'smart-energy-meter-7b5a0.firebasestorage.app',
    iosBundleId: 'com.example.flutterSmartEnergyMeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx6aZ8WyrJmPuXishthAiTpxK-awVEn9A',
    appId: '1:846220520693:ios:293ec9815ab46b9572a9bc',
    messagingSenderId: '846220520693',
    projectId: 'smart-energy-meter-7b5a0',
    databaseURL: 'https://smart-energy-meter-7b5a0-default-rtdb.firebaseio.com',
    storageBucket: 'smart-energy-meter-7b5a0.firebasestorage.app',
    iosBundleId: 'com.example.flutterSmartEnergyMeter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsHWEKq2WTiIDzQ0t-K6l6Lhvvp1kQF_k',
    appId: '1:846220520693:web:585b3ee52b6df49672a9bc',
    messagingSenderId: '846220520693',
    projectId: 'smart-energy-meter-7b5a0',
    authDomain: 'smart-energy-meter-7b5a0.firebaseapp.com',
    databaseURL: 'https://smart-energy-meter-7b5a0-default-rtdb.firebaseio.com',
    storageBucket: 'smart-energy-meter-7b5a0.firebasestorage.app',
    measurementId: 'G-03NXETL3FV',
  );
}
